"""convert_images_to_binary

Revision ID: a1b2c3d4e5f6
Revises: 1f7f62595c4d
Create Date: 2026-04-07 23:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import LargeBinary


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '1f7f62595c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new binary column for image data
    op.add_column('pets', sa.Column('image_data', LargeBinary(), nullable=True))
    
    # Migrate existing image files to binary data
    connection = op.get_bind()
    
    # Import here to avoid circular imports
    import os
    from PIL import Image
    
    # Get upload folder from config
    upload_folder = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 
                                'app', 'static', 'uploads', 'pets')
    
    # Fetch all pets with image_url
    result = connection.execute(sa.text("SELECT id, image_url FROM pets WHERE image_url IS NOT NULL AND image_url != ''"))
    
    for row in result:
        pet_id, image_url = row
        if image_url:
            image_path = os.path.join(upload_folder, image_url)
            if os.path.exists(image_path):
                try:
                    with open(image_path, 'rb') as f:
                        image_data = f.read()
                    connection.execute(
                        sa.text("UPDATE pets SET image_data = :data WHERE id = :id"),
                        {"data": image_data, "id": pet_id}
                    )
                    print(f"Migrated image for pet {pet_id}")
                except Exception as e:
                    print(f"Error migrating image for pet {pet_id}: {e}")
    
    # Drop the old image_url column
    op.drop_column('pets', 'image_url')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the image_url column
    op.add_column('pets', sa.Column('image_url', sa.String(length=255), nullable=True))
    
    # Note: In downgrade, we can't easily convert binary back to files
    # So we'll just set image_url to NULL for all records
    # The user would need to re-upload images
    
    # Drop the image_data column
    op.drop_column('pets', 'image_data')
    
    # ### end Alembic commands ###
